import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'

const CONTENT_ROOT = path.resolve('content')
const OUTPUT_FILE = path.resolve('src/data/posts.generated.js')
const LOCALES = ['zh', 'en']

const formatDate = (value) => {
  if (value instanceof Date) {
    const y = value.getUTCFullYear()
    const m = String(value.getUTCMonth() + 1).padStart(2, '0')
    const d = String(value.getUTCDate()).padStart(2, '0')
    return `${y}.${m}.${d}`
  }

  if (typeof value === 'string') {
    const clean = value.trim()
    if (/^\d{4}-\d{2}-\d{2}$/.test(clean)) {
      const [y, m, d] = clean.split('-')
      return `${y}.${m}.${d}`
    }
    if (/^\d{4}-\d{2}-\d{2}T/.test(clean)) {
      const parsed = new Date(clean)
      if (!Number.isNaN(parsed)) {
        return formatDate(parsed)
      }
    }
  }

  return value
}

const readPostsFromDirectory = (directory) => {
  if (!directory || !fs.existsSync(directory)) {
    return []
  }

  const files = fs.readdirSync(directory).filter((file) => file.endsWith('.md'))

  return files.map((file) => {
    const fullPath = path.join(directory, file)
    const raw = fs.readFileSync(fullPath, 'utf8')
    const { data, content } = matter(raw)
    const { id, title, date, tags = [], category = 'posts', featured = false, excerpt = '' } = data

    if (!id || !title || !date) {
      throw new Error(`Missing required frontmatter (id, title, date) in ${path.relative(process.cwd(), fullPath)}`)
    }

    const safeDate = formatDate(date)

    return {
      id,
      title,
      date: safeDate,
      tags,
      category,
      featured,
      excerpt,
      content: content.trim(),
    }
  })
}

const resolveContentDirectory = (locale) => {
  const localizedDir = path.join(CONTENT_ROOT, locale)
  if (fs.existsSync(localizedDir) && fs.statSync(localizedDir).isDirectory()) {
    return localizedDir
  }

  if (locale === 'zh') {
    return CONTENT_ROOT
  }

  return null
}

const parseForSort = (value) => {
  const normalized = typeof value === 'string' ? value.replaceAll('.', '-') : value
  const stamped = typeof normalized === 'string' ? `${normalized}T00:00:00Z` : normalized
  const parsed = new Date(stamped)
  return Number.isNaN(parsed) ? 0 : parsed.getTime()
}

const sortPosts = (posts) => {
  const sorted = [...posts]
  sorted.sort((a, b) => parseForSort(b.date) - parseForSort(a.date))
  return sorted
}

const mergeLocalizedPost = (basePost, localizedPost) => {
  if (!basePost) {
    return localizedPost
  }

  if (!localizedPost) {
    return basePost
  }

  return {
    ...basePost,
    ...localizedPost,
    title: localizedPost.title || basePost.title,
    date: localizedPost.date || basePost.date,
    tags: localizedPost.tags?.length ? localizedPost.tags : basePost.tags,
    category: localizedPost.category || basePost.category,
    featured: localizedPost.featured ?? basePost.featured,
    excerpt: localizedPost.excerpt || basePost.excerpt,
    content: localizedPost.content || basePost.content,
  }
}

const localePosts = Object.fromEntries(
  LOCALES.map((locale) => [locale, readPostsFromDirectory(resolveContentDirectory(locale))]),
)

if (!localePosts.zh.length) {
  console.log('No markdown files found for the default locale. Add .md files under /content or /content/zh and rerun.')
  process.exit(0)
}

const zhPosts = sortPosts(localePosts.zh)
const zhPostsById = new Map(zhPosts.map((post) => [post.id, post]))
const enPostsById = new Map(localePosts.en.map((post) => [post.id, post]))

const postsByLocale = {
  zh: zhPosts.map((post) => ({
    ...post,
    locale: 'zh',
    sourceLocale: 'zh',
    isFallback: false,
  })),
  en: sortPosts(
    Array.from(new Set([...zhPostsById.keys(), ...enPostsById.keys()])).map((id) => {
      const basePost = zhPostsById.get(id)
      const localizedPost = enPostsById.get(id)
      const mergedPost = mergeLocalizedPost(basePost, localizedPost)

      return {
        ...mergedPost,
        locale: 'en',
        sourceLocale: localizedPost ? 'en' : 'zh',
        isFallback: !localizedPost,
      }
    }),
  ),
}

const defaultPosts = postsByLocale.zh

const output = `// Auto-generated by npm run import-md. Do not edit manually.\n\nexport const postsByLocale = ${JSON.stringify(postsByLocale, null, 2)}\n\nexport const posts = postsByLocale.zh\n\nexport default posts\n`

fs.writeFileSync(OUTPUT_FILE, output)
console.log(
  `Generated ${defaultPosts.length} zh posts and ${postsByLocale.en.length} en posts -> ${path.relative(process.cwd(), OUTPUT_FILE)}`,
)
